karaoke_online_hakaton/app/routes.py
from flask import Flask, render_template, Blueprint, url_for, redirect, session, request

general = Blueprint('general', __name__)


@general.route('/')
def index():
    return "what's up!"


@general.route('/speech')
def speech():
    return render_template('speech.html')

karaoke_online_hakaton/application/routes.py
import mongoengine
from flask import Flask, render_template, Blueprint, send_from_directory, abort, jsonify, request
from flask_security import login_required
from DataBase import *
from forms import *
from helper_function import spanify_text
from config import Config
import datetime
import stripe
import hashlib

stripe.api_key = "sk_test_51ICUYQBfTYBgs6VwHo83UJHU3bHRslQjyB8ghSSK0QNXQ0WSLx5IFBg79s2FGgUBGP16VDTWSGpeJoCoz7BQrS2L00GCcjuzWi"

default_timer = datetime.datetime(year=2018, month=7, day=12, hour=7, minute=9, second=33)

from karaoke_online_hakaton import avatars

general = Blueprint('general', __name__)

def ranking():
    ranker = 1
    users = User.objects().order_by('-points')
    for user in users:
        user.rank = ranker
        ranker += 1
        user.save()


def check_energy():
    user = User.objects(id=current_user.id)[0]

    energy = user.energy

    timedelta = datetime.datetime.now() - user.energy_date

    if energy < 10:
        if user.energy_date == default_timer:
            user.energy_date = datetime.datetime.now()
        elif timedelta.days >= 1 and user.energy_date != default_timer:
            user.energy = 10
            user.energy_date = default_timer
    user.save()


def daily_gift():
    user = User.objects(id=current_user.id)[0]

    if user.daily_gift_date == default_timer:
        user.daily_gift_date = datetime.datetime.now()
        user.points += 500

    timedelta = datetime.datetime.now() - user.daily_gift_date

    if timedelta.days >= 1 and user.daily_gift_date != default_timer:
        user.daily_gift_date = default_timer

    user.save()


@general.route('/')
def index():
    return render_template("mainpage.html", default_timer=default_timer)


@general.route('/lobby')
@login_required
def lobby():
    q = request.args.get("q")

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        songs = Song.objects(name_contains=q)
    else:
        songs = Song.objects()

    pages = songs.paginate(page=page, per_page=10)

    user = User.objects(id=current_user.id)[0]

    energy = user.energy

    check_energy()

    daily_gift()

    return render_template("lobby.html", songs=songs, pages=pages, energy=energy, daily_gift_date=user.daily_gift_date,
                           default_timer=default_timer)


@general.route('/profile', methods=["GET", "POST"])
def profile():
    return render_template('profile.html')


@general.route("/profile/SungSongs")
def SungSongs():
    user = User.objects(id=current_user.id)[0]
    return render_template('sungsongs.html', songs=user.sung_songs)


@general.route("/shop", methods=["GET", "POST"])
def shop():
    q = request.args.get("q")

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        things = Shop.objects(name__contains=q)
    else:
        things = Shop.objects()

    pages = things.paginate(page=page, per_page=1)

    form = BuyStyleForm()
    if form.validate_on_submit():
        style_id = form.bthing.data
        user = User.objects(id=current_user.id)[0]
        style = Shop.objects(id=style_id)[0]
        if user.points >= style.cost and not style in user.bought_styles:
            user.points = user.points - style.cost
            user.bought_styles.append(style)
            user.save()
            return redirect(url_for("general.index"))

    return render_template("shop.html", pages=pages, form=form)


@general.route("/mystuff", methods=["GET", "POST"])
def mystuff():
    q = request.args.get("q")


    if q:
        things = Shop.objects(name__contains=q, )
    else:
        things = Shop.objects()




    return render_template("mystuff.html", things=things)


@general.route('/<song_id>')
@login_required
def speech(song_id):
    try:
        song = Song.objects(id=song_id)[0]

        text = spanify_text(song)

        user = User.objects(id=current_user.id)[0]

        user.energy -= 1
        energy = user.energy
        user.save()

        return render_template('speech.html', song=song, ly=text)

    except mongoengine.errors.ValidationError as e:
        print(e)
        abort(404)


@general.route('/submit_song', methods=('POST', 'GET'))
def submit_song():
    data = request.json

    user = User.objects(id=current_user.id)[0]
    song = Song.objects(id=data['song_id'])[0]

    sung = SungSong(song=song, score=data['percentage'])
    print(user.points)
    print(type(user.points))
    user.points += data['percentage'] * 1.5 ** song.difficulty

    user.sung_songs.append(sung)
    user.save()

    return jsonify('Your result has been saved!')


@general.route('/avatars/<path:filename>')
def get_avatar(filename):
    print('lmao')
    print(send_from_directory('karaoke_online_hakaton/static/avatars', filename))
    return send_from_directory('karaoke_online_hakaton/static/avatars', filename)


@general.route('/profile/edit', methods=('POST', 'GET'))
def editprofile():
    form = NewUserNameForm()
    if form.validate_on_submit():
        new_name = form.username.data
        user = User.objects(id__contains=current_user.id)
        user.update(set__username=str(new_name))
        return redirect(url_for("general.profile"))

    avatar_form = UploadAvatarForm()
    if request.method == 'POST':
        f = request.files.get('file')
        raw_filename = avatars.save_avatar(f)
        user = User.objects(id=current_user.id)[0]
        user.avatar_filename = raw_filename
        user.save()
        return redirect(url_for("general.profile"))

    return render_template("editprofile.html", form=form, avatar_form=avatar_form)


@general.route('/about')
def about_us():
    return render_template('about.html')


@general.route('/premium')
def premium():
    return render_template('premium.html')


@general.route('/stripe_pay/<product_id>')
def stripe_pay(product_id):
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[{
            'price': product_id,
            'quantity': 1,
        }],
        mode='subscription',
        success_url=url_for('general.thanks', _external=True) + '?session_id={CHECKOUT_SESSION_ID}',
        cancel_url=url_for('general.premium', _external=True, product_id=product_id),
    )
    return {'checkout_session_id': session['id'], 'checkout_public_key': Config.STRIPE_PUBLIC_KEY}


@general.route('/thanks')
def thanks():
    return render_template('thanks.html')

@general.route('/leaderboard')
def leaderboard():

    q = request.args.get("q")

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        users = User.objects(username__contains=q).order_by('-points')
    else:
        users = User.objects(points__gt=0).order_by('-points')


    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1


    pages = users.paginate(page=page, per_page=10)

    ranking()

    return render_template('LeaderBoard.html', pages=pages, users=users)


@general.route('/friendlist', methods = ("GET", "POST"))
def friendlist():
    user = User.objects(id=current_user.id)[0]
    q = request.args.get("q")
    roomid=''

    if request.method == "POST":
        data = request.form['friend_name']
        friend = User.objects(username__contains=data).order_by('-points')[0]
        roomid=hashlib.md5(friend.username.encode()).hexdigest()
        print(roomid)
        if user.username not in friend.friendrequests and user.username not in friend.friendlist:
            friend.friendrequests.append(user.username)
            user.friendrequests.append(friend.username)
            user.save()
            friend.save()




    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    search = False

    if q:
        users = User.objects(username__contains=q).order_by('-points')
        search = True
    else:
        users = User.objects(friendlist__contains=user.username).order_by('-points')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    pages = users.paginate(page=page, per_page=10)





    return render_template('friendlist.html', pages=pages, users=users, search=search, roomid=roomid)




@general.route('/friendrequest', methods = ("GET", "POST"))
def friendrequest():
    user = User.objects(id=current_user.id)[0]
    q = request.args.get("q")

    if request.method == "POST":
        data = request.form['friend_name']
        friend = User.objects(username__contains=data).order_by('-points')[0]
        if user.username in friend.friendrequests:
            friend.friendlist.append(user.username)
            friend.friendrequests.remove(user.username)
            friend.save()
            user.friendlist.append(friend.username)
            user.friendrequests.remove(friend.username)
            user.save()


    users = User.objects

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        requests = User.objects(username__contains=q, friendrequests__contains=user.username).order_by('-points')
    else:
        requests = User.objects(friendrequests__contains=user.username).order_by('-points')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    pages = requests.paginate(page=page, per_page=10)





    return render_template('friendrequests.html', pages=pages, requests=requests)


@general.route('/chatting/<username>')
def chatting(username):
    my_username = User.objects(id=current_user.id)[0].username
    HASH=hashlib.md5("".join(sorted([my_username, username])).encode()).hexdigest()
    print(HASH)

karaoke_online_hakaton/templates/LeaderBoard.html
{% extends 'BaseTemplate.html' %}

{% block content %}

<div class="container">

    <div class="row justify-content-md-center">
        <form class="form-inline my-2 my-lg-0">
            <div class="card-body">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" name="q"
                       value="{{ request.args.get('q', '') }}">
                <button class="btn btn-success" type="submit">Search</button>
            </div>
        </form>
    </div>

    <div class="card border-success mb-3">
        <div class="text-center">
            <div class="header">
                <div class="row justify-content-md-center">
                        {% for user in pages.items %}
                            {{ user.rank }}
                            {{ user.username }}
                            $ {{ user.points }}<br>
                        {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <ul class="list-group list-group-flush">
        <div class="container">
            <div class="row justify-content-md-center">
                <nav aria-label="Page navigation">
                    {% if not pages.items %}
                    <h1 style="color:white;" align="center">No Poll like that</h1>
                    <div align="center">
                        <img src="https://publicdomainvectors.org/photos/feels.png" height="500" width="500">
                    </div>
                    {% endif %}
                    <ul class="pagination">
                        {% if pages.has_prev %}
                        <li class="page-item">

                            <a class="page-link"
                               href="?{% if request.args.get('q', '') %}q={{ request.args.get('q', '') }}&{% endif %}page={{ pages.prev_num }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% endif %}
                        {% if pages.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?{% if request.args.get('q', '') %}q={{ request.args.get('q', '') }}&{% endif %}page={{ pages.next_num }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
</div>


{% endblock %}

karaoke_online_hakaton/templates/about.html
{% extends 'BaseTemplate.html' %}

{% block content %}
<div class="container">
    <h1 justify="nw">О Нас и о наших достижениях</h1>
    <div class="card mb-3">
        <h3 class="card-header">Проект и его функционал</h3>
          <div class="card-body">
              <img src="{{ url_for('static', filename='img/Karaoke_about.jpg') }}", alt="Programming", style="width:1065px;height:500px;">
            <h5 class="card-title">Для чего наш проект?</h5>
            <h5 class="card-subtitle text-muted">В связи с тем что число заболевших COVID-19 в мире превысило 50 млн человек.Мы решили не лишать удовольствия людей которые любят петь и создали сайт-"Караоке-Онлайн".На нем можно найти свою любимую песню, также можно посоревноваться со своими друзьями,чем лучше спел тем больше заработал балов, добавили магазин в котором будут нахоиться предметы которые вы сможе купить за внутриигровую валюту.
            </h5>
          </div>
        </div>
    <div class="card mb-3">
        <h3 class="card-header">На чем мы писали:</h3>
          <div class="card-body">
              <img src="{{ url_for('static', filename='img/Python.jpg') }}", alt="Programming", style="width:1065px;height:500px;">
            <h5 class="card-title">Язык программирования Python</h5>
            <h5 class="card-subtitle text-muted">Высокоуровневый язык программирования общего назначения, ориентированный на повышение производительности разработчика и читаемости кода. Синтаксис ядра Python минималистичен. В то же время стандартная библиотека включает большой набор полезных функций.</h5>
          </div>
        </div>
    <div class="card mb-3">
        <h3 class="card-header">Community</h3>
          <div class="card-body">
            <h5 class="card-title">О нашей команде</h5>
            <h6 class="card-subtitle text-muted">Who do this</h6>
              <h3>"Видео с ютуба"</h3>
          </div>
        </div>
{% endblock %}

karaoke_online_hakaton/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible", content="ie=edge">
    <link rel="stylesheet", href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% block title %}{% endblock %}
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Company name</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="#">Features</a>
    <a class="p-2 text-dark" href="#">Enterprise</a>
    <a class="p-2 text-dark" href="#">Support</a>
    <a class="p-2 text-dark" href="#">Pricing</a>
  </nav>
  <a class="btn btn-outline-primary" href="#">Sign up</a>
</div>

<div class="alert alert-info" role="alert">
  Text
  Text
  Text
  Text
  Text
  Text
  Text
  Text
  Text
  Text
  Text
  Text
  Text
  Text
  Text
  Text
</div>

<div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">текст</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">текст</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">текст.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
  </body>
</html>

karaoke_online_hakaton/templates/chatting.html
<html>
{% extends "BaseTemplate.html" %}

{% block content %}

<title>Chat Room</title>
<script src="https://cdn.socket.io/3.1.3/socket.io.min.js"
        integrity="sha384-cPwlPLvBTa3sKAgddT6krw0cJat7egBga3DJepJyrLl4Q9/5WLra3rrnMcyTyOnh"
        crossorigin="anonymous"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
</script>
<script type="text/javascript">
$(document).ready(function() {

	var socket = io.connect('http://127.0.0.1:5000');
    let roomid = "{{roomID}}"
    let username = "{{current_user.username}}"

	socket.on('connect', function() {
		socket.emit( 'join_room',{roomid: roomid, username: username});
		console.log('User has connected!')
	});

	socket.on('chatmessage_get', function(data) {
		$("#messages").append('<li>'+ data["username"]+ ": " +data["msg"]+'</li>');
		console.log('Received message');
	});

	$('#sendbutton').on('click', function() {
		socket.emit('chatmessage', {username: username ,msg: $('#myMessage').val(), roomid: roomid});
		$('#myMessage').val('');
	});

});
</script>
<div class="container">
    <div class="card border-success mb-3">

        <div class="card mb-3">
            <div class="card-body" style="margin:20px">

                <div class="card border-success mb-3" style="margin: 10px">
                    <div class="card bg-secondary mb-3" style="margin: 10px !important">
                        <div id="lyrics-container" style="overflow-y: scroll; height: 550px">

                            <ul class="list-group" id="messages" style="color: MediumSpringGreen">

                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3">
        <div class="card-body">
            <div class="text-center">
                <div class="row justify-content-md-center">
                    <form class="form-inline my-2 my-lg-0">
                        <input type="text" class="form-control" placeholder="Message" id="myMessage"
                               style="color: MediumSeaBlue">
                    </form>
                    <button class="btn btn-outline-success" id="sendbutton">Send</button>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}
</html>

karaoke_online_hakaton/templates/lobby.html
{% extends "BaseTemplate.html" %}

{% block content %}
    {% if current_user.is_authenticated %}
    {% if daily_gift_date == default_timer %}

    <div class="modal" id='genana'>
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="row justify-content-md-center">
                        <button type="button" style="width:496" class="btn btn-outline-warning btn-lg btn-block"> Daily
                            Gift
                        </button>
                    </div>
                </div>
                <div class="modal-body">
                    <p>Your Daily Gift(500$) is ready!</p>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-outline-success"> Get!</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('#genana').modal('show')

    </script>

    {% endif %}
    {% endif %}

<div class="container">
    <div class="row justify-content-md-center">
        <button type="button" class="btn btn-outline-warning">  {{ energy }}  </button>
    </div>
    <div class="row justify-content-md-center">
        <form class="form-inline my-2 my-lg-0">
            <div class="card-body">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" name="q"
                       value="{{ request.args.get('q', '') }}">
                <button class="btn btn-success" type="submit">Search</button>
            </div>
        </form>
    </div>

    <div class="card border-success mb-3">

        <div class="text-center">
            <div class="header">
                {% for song in pages.items %}
                <a href="{{ url_for('general.speech', song_id=song.id) }}" style="font-size: 25px">{{ song.name
                    }}
                    {% if song.difficulty == 1 %}
                </a> <span class="badge badge-success" style="font-size: 17">Easy</span> <br>
                {% endif %}
                {% if song.difficulty == 2 %}
                </a> <span class="badge badge-warning" style="font-size: 17">Medium</span> <br>
                {% endif %}
                {% if song.difficulty == 3 %}
                </a> <span class="badge badge-danger" style="font-size: 17">Hard</span> <br>
                {% endif %}


                {% endfor %}
            </div>
        </div>
    </div>

    <ul class="list-group list-group-flush">
        <div class="container">
            <div class="row justify-content-md-center">
                <nav aria-label="Page navigation">
                    {% if not pages.items %}
                    <h1 style="color:white;" align="center">No Poll like that</h1>
                    <div align="center">
                        <img src="https://publicdomainvectors.org/photos/feels.png" height="500" width="500">
                    </div>
                    {% endif %}
                    <ul class="pagination">
                        {% if pages.has_prev %}
                        <li class="page-item">

                            <a class="page-link"
                               href="?{% if request.args.get('q', '') %}q={{ request.args.get('q', '') }}&{% endif %}page={{ pages.prev_num }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% endif %}
                        {% if pages.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?{% if request.args.get('q', '') %}q={{ request.args.get('q', '') }}&{% endif %}page={{ pages.next_num }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </ul>
        </div>
    </div>
</div>


{% endblock %}

karaoke_online_hakaton/templates/profile.html
{% extends 'BaseTemplate.html' %}

{% block content %}
<div class="container">
    <div class="card border-success mb-3">
        <div class="card-mb-3"
        <div class="row justify-content-md-center">
            <div class="card-header">
                <div class="row justify-content-md-center">
                    <span class="badge badge-danger" style="font-size: 35"> {{ current_user.username }}</span>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="card border-info mb-3" style="max-width: 15rem; margin: 0 auto; border: 0 !important;">
                {% if current_user.avatar_filename == None %}
                <img src="{{ avatars.robohash(current_user.username, size=250) }}">
                {% else %}
                <img src="/static/avatars/{{ current_user.avatar_filename }}" width="250" height="250">
                {% endif %}
            </div>
        </div>
        <div class="card-body">
            <ul class="list-group list-group-flush">

                <li class="list-group-item">
                    <div class="row">
                        <span class="badge badge-dark" style="font-size: 25">Sung songs </span>
                        <a href="{{ url_for('general.SungSongs') }}">
                            <button type="button" class="btn btn-outline-success">Check</button>
                        </a>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <span class="badge badge-dark" style="font-size: 25">Achievments </span>
                        <a href="{{ url_for('general.SungSongs') }}">
                            <button type="button" class="btn btn-outline-info">Check</button>
                        </a>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <span class="badge badge-dark" style="font-size: 25">Customize </span>
                        <a href="{{ url_for('general.shop') }}">
                            <button type="button" class="btn btn-outline-warning" style="margin:2">Shop</button>
                        </a>
                        <a href="{{ url_for('general.mystuff') }}">
                            <button type="button" class="btn btn-outline-danger" style="margin:2">My stuff</button>
                        </a>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <span class="badge badge-dark" style="font-size: 25">Premium </span>
                        <a href="{{ url_for('general.premium') }}">
                            <button type="button" class="btn btn-warning">Get</button>
                        </a>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <a href="{{ url_for('general.editprofile') }}">
                            <button type="button" class="btn btn-outline-success">Edit Profile</button>
                    </div>
                </li>
            </ul>

            </ul>
        </div>
    </div>
</div>

{% endblock %}

karaoke_online_hakaton/templates/sungsongs.html
{% extends "BaseTemplate.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <form class="form-inline my-2 my-lg-0">
            <div class="card-body">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" name="q"
                       value="{{ request.args.get('q', '') }}">
                <button class="btn btn-success" type="submit">Search</button>
            </div>
        </form>
    </div>

    <div class="card border-success mb-3">

        <div class="text-center">
            <div class="header">
                {% for song in songs %}


                <a href="{{ url_for('general.speech', song_id=song.id) }}" style="font-size: 25px">{{ song.song.name
                    }} - {{ song.song.author }} </a>                     {% if song.song.difficulty == 1 %}
                </a> <span class="badge badge-success" style="font-size: 17">Easy</span> <br>
                {% endif %}
                {% if song.song.difficulty == 2 %}
                </a> <span class="badge badge-warning" style="font-size: 17">Medium</span> <br>
                {% endif %}
                {% if song.song.difficulty == 3 %}
                </a> <span class="badge badge-danger" style="font-size: 17">Hard</span> <br>
                {% endif %}
                <span class="score">{{ song.score }}%</span><br>
                <span id='date' style="font-size: 11px; float: right">{{ song.date.strftime('%X %x') }}</span>
                <hr style="border-top: 1px solid rgb(188 185 185 / 25%); margin-bottom: 0;">

                <script>
                    function getGreenToRed(percent){
                        r = percent<50 ? 255 : Math.floor(255-(percent*2-100)*255/100);
                        g = percent>50 ? 255 : Math.floor((percent*2)*255/100);
                        return 'rgb('+r+','+g+',0)';
                    }

                    document.querySelectorAll('.score')[document.querySelectorAll('.score').length - 1].style.color = getGreenToRed({{ song.score }})
                </script>

                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}